Cargo.lock, Cargo.toml, shell/_swap-cli, shell/_swap-cli.ps1, src/bin/farcasterd.rs, src/bin/peerd.rs, src/bin/swap-cli.rs, src/cli/command.rs, src/cli/opts.rs, src/farcasterd/runtime.rs, src/peerd/opts.rs, src/rpc/client.rs, src/rpc/messages.rs, src/rpc/request.rs, src/swapd/runtime.rs
=>  Create Alice and Bob session params + min unencrypted wallet

src/bin/swapd.rs, src/bin/syncerd.rs, src/rpc/request.rs, src/swapd/opts.rs, src/swapd/runtime.rs, src/syncerd/opts.rs, src/syncerd/runtime.rs
Also removes key_opts and key file access from swapd and syncerd
=> Remove node_id from swapd and syncerd

Cargo.toml, build.rs, src/bin/walletd.rs, src/error.rs, src/lib.rs, src/rpc/request.rs, src/service.rs, src/walletd/mod.rs, src/walletd/opts.rs, src/walletd/runtime.rs
Walletd should eventually manage secrets and signing. Currently, just implement some scaffolding and primitive functionality:
- Add a token to authenticate actions on walletd
- Return secrets upon request
- Return node_id upon request
=> Add Walletd daemon

src/bin/walletd.rs
... and cleanup its log message
=> Walletd: Remove unused var

Dockerfile, README.md
Change the dockerfile and add some documentation on README
=> Rework docker support

Cargo.lock, Cargo.toml, src/cli/command.rs, src/error.rs, src/farcasterd/runtime.rs, src/peerd/runtime.rs, src/rpc/request.rs, src/service.rs, src/swapd/opts.rs, src/swapd/runtime.rs, src/swapd/storage/disk.rs, src/swapd/storage/driver.rs, src/syncerd/runtime.rs, src/walletd/runtime.rs
Uses a local fork of rust-internet2 not yet public
=> Enable the generic peer messaging

Cargo.lock, Cargo.toml, src/farcasterd/runtime.rs, src/rpc/request.rs, src/swapd/runtime.rs, src/walletd/runtime.rs
Published all repos to github to align the dependencies
=> bumped version, V0.0.2

shell/_swap-cli, shell/_swap-cli.ps1, src/cli/opts.rs, tests/rpc.rs
Fixes integration test after formatting change.
=> Align amount format for arbitrating & accordant values

sequencediagram.txt, src/cli/opts.rs, src/swapd/runtime.rs, src/walletd/runtime.rs
=> Completes message sequence when Alice is Maker as well as Bob is Maker

Cargo.lock, Cargo.toml, src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs, src/syncerd/syncer_state.rs
Monero Syncer implementation.
No support for runing a monero syncerd yet - this requires extra configuration.
=> Monero Syncer

sequencediagram.txt, src/rpc/request.rs, src/swapd/runtime.rs, src/syncerd/bitcoin_syncer.rs, src/syncerd/mod.rs, src/syncerd/monero_syncer.rs, src/syncerd/runtime.rs, src/syncerd/syncer_state.rs, src/syncerd/types.rs, src/walletd/runtime.rs
=> Cancel path 1

Cargo.lock, src/swapd/runtime.rs, src/walletd/runtime.rs
This points to my fork for now, waiting on https://github.com/farcaster-project/farcaster-core/pull/133 to be merge into core, hence the draft.
=> Update with latest version of core

Cargo.lock, src/rpc/request.rs, src/swapd/runtime.rs, src/walletd/runtime.rs, tests/functional.rs
Based on https://github.com/farcaster-project/farcaster-core/pull/143
=> Verify DLEQ proofs after reveal

README.md, doc/README.md, doc/docker-stack.md, doc/local-swap.md, docker-compose.yml
Move some documentation regarding Docker and docker-compose.
Add a docker-compose file to run farcasterd and the Monero wallet rpc inside containers (images from /containers and this repo).
=> Add docker compose and doc

Cargo.lock, src/bin/syncerd.rs, src/bin/walletd.rs, src/cli/command.rs, src/cli/opts.rs, src/farcasterd/runtime.rs, src/rpc/request.rs, src/swapd/runtime.rs, src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs, src/syncerd/opts.rs, src/syncerd/syncer_state.rs, src/syncerd/types.rs, src/walletd/runtime.rs, tests/functional.rs
=> Use correct aggregated monero keys

.github/workflows/test.yml, shell/_swap-cli, shell/_swap-cli.ps1, src/cli/opts.rs, tests/functional.rs, tests/rpc.rs
Still untested, not that trivial to get the functional tests running, since the transaction needs to be sent out successfully.
=> Sweep address

tests/functional.rs
The interprocess port might not be freed in time before running the next test case. Ensure this is not a problem by namespacing the ports for different tests.
This is not a problem in the normal syncer, since the port is re-used for all tasks.
=> Syncer: namespace zmq sockets in functional test

Cargo.toml, doc/local-swap.md
Update doc and run `dprint fmt`
=> Update doc local swap

src/opts.rs
Fix #155
Data directory expansion was missing when creating the data directory for the microservices.
=> Fix data dir folder creation

doc/local-swap.md, docker-compose.yml
Use ssl to talk to external node.
=> Use ssl testnet blockstream node

src/swapd/runtime.rs
=> swapd: avoid trying cancelling after successful swap

src/swapd/runtime.rs
reuses pending_request: its getting dangerous
=> swapd: wait sweep_monero_thr blocks before sweeping the monero

README.md, doc/local-swap.md
=> Small doc adjustments

src/swapd/runtime.rs
Added many more state predicates at the level of the handling the requests
This allowed to remove a lot of the nesting
=> Swapd state management improvement

README.md, doc/docker-stack.md, doc/local-swap.md, docker-compose.yml
Fixes a list of issues regarding documentation about usage and Docker/Docker compose.
Add a list (non-exhaustive) of usable public infrastructure and documentation about running Monero wallet RPC with Docker.
=> Doc adjustments batch 2

src/swapd/runtime.rs
Resolve the minors errors raised by clippy.
=> Fix clippy errors

src/farcasterd/runtime.rs
squash! farcasterd: rm terminated syncer key from syncer_clients
=> farcasterd: rm terminated syncer key from syncer_clients

src/swapd/runtime.rs, src/syncerd/syncer_state.rs, src/syncerd/types.rs, tests/functional.rs
This was more an exercise for myself than actually yielding much benefit. Especially the `SyncerBlockHeight` type is a bit unwieldy. Should I split their implementation into separate commits an PRs?
=> Syncer TaskId

.github/workflows/test.yml, Cargo.lock, Cargo.toml, tests/functional-swap.rs
Adds a functional tests that runs four swaps in parallel (2 with Bob maker, 2 with Alice maker).
=> Add parallel swap test

src/farcasterd/runtime.rs, src/peerd/runtime.rs, src/service.rs, src/swapd/runtime.rs, src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs, src/syncerd/runtime.rs, src/walletd/runtime.rs, tests/functional.rs
Fix #279, fix #257, fix #170 
Modify logs to resolve cited issues.
Cancel with refund/punish path have not been tested here, but I think most of the work will be reused already and it can come in a later PR.
=> Log levels

src/walletd/runtime.rs
Aggregate the two partial view keys on refund path:
```rust
let view_key = view_key_alice + view_key_bob;
```
=> Compute full xmr secret view key on refund path

src/syncerd/monero_syncer.rs, src/walletd/runtime.rs
Fix #306
Also fix corresponding address after extracting secrets from Buy and Refund (follow up of #302)
=> Fix wrong sweeped address in logs

README.md, doc/README.md, doc/install-guide.md, doc/local-swap.md
Depends on #329 and #331
Fix #324, fix #325, fix #326, fix #327, fix #328, fix #333
Add bigger documentation on how to install from sources and use the node with docker-compose.
=> Documenting installation

.github/workflows/create-release.yml, .github/workflows/package.yml, CHANGELOG.md
Fix  #171
Add some log in changelog for initial release. Update CI to push version tagged faracasterd image.
**When this is merged we can trigger the release with the CI and try to do the version `0.1.0` when we have everything in `main`**
=> Prepare release

.github/workflows/create-release.yml
Disable the publish on crates until monero rpc is on crates too.
=> Do not try to publish on crates with github deps

src/bin/peerd.rs, src/farcasterd/runtime.rs, src/peerd/runtime.rs, src/rpc/request.rs
=> Peer info: Use remote address to assemble internal id

src/farcasterd/runtime.rs
LaunchSwap message handling routine was very convoluted, touching state that is not needed and could end up recreating the actual address twice.
=> Farcasterd: Simplify LaunchSwap peer ServiceId recreation

tests/functional.rs
To test that the minimum amount is respected, first send an XMR amount below to required minimum to the sweep address, then send another amount to complete the required minimum. The syncer should only send a single event for the sweep of the entire amount, and not two events. A second, non-blocking receive on the zmq socket should therefore error. Closes #423 .
=> Syncer functional test: Test sweep minimum amount

README.md
Fix #431
We have unsafe code at least in peerd to handle connections, we cannot leave this badge for now. I guess I added it too quickly :)
=> Remove unsafe forbidden badge

src/error.rs, src/swapd/runtime.rs, src/swapd/syncer_client.rs, src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs, src/syncerd/syncer_state.rs, src/syncerd/types.rs, src/walletd/runtime.rs, tests/functional.rs
Part of #493 , the sweep btc functionality is implemented to eventually allow for recovery of funds stuck in the funding address.
=> Syncer: Sweep Btc

doc/README.md, doc/swap_state_machine.svg, doc/swap_state_machine.txt
This sets out to document the state transitions and states of the swapd state machine. Arrows are labeled with messages, events and requests that trigger the actual transitions.
=> Docs: Start documenting the swapd state machine

shell/_swap-cli, shell/_swap-cli.ps1, shell/swap-cli.bash, src/cli/command.rs, src/cli/opts.rs, src/farcasterd/runtime.rs, src/rpc/request.rs, src/swapd/runtime.rs, src/swapd/swap_state.rs, tests/functional-swap.rs
=> Naming: Rename cancel swap to abort swap

README.md, dprint.json, farcasterd.toml, tests/cfg/electrs.toml
Ran formatter on markdown files.
=> Style: update dprints formater and run fmt on *.md files

src/databased/runtime.rs
Checkpoint removal used to log an `Error` every time a swap was cleaned up and no checkpoint data for the swap had been written yet. This PR relegates this database log to `Debug`.
=> Database: Log debug, not error, when removed entry does not exist

Cargo.lock, Cargo.toml
Use farcaster-core main branch
=> Deps: Bump strict encoding to 0.8.1

.github/workflows/create-release.yml, .github/workflows/draft-new-release.yml
Update the draft and create release CI workflows.
=> ci: update workflows, remove release bins

src/syncerd/bitcoin_syncer.rs
Also correct comments for documentation
=> Syncer: Cast from height without unwrap

.github/workflows/test.yml, src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs, src/syncerd/types.rs, tests/bitcoin.rs, tests/cfg/config.yml, tests/cfg/electrs.toml, tests/docker-compose.yml, tests/monero.rs, tests/swap.rs, tests/utils/fc.rs
Use latest Bitcoin, Electrs, and Monero versions
=> ci: bumps containers in tests

src/bin/peerd.rs, src/cli/command.rs, src/databased/runtime.rs, src/farcasterd/runtime.rs, src/grpcd/runtime.rs, src/opts.rs, src/peerd/runtime.rs, src/rpc/client.rs, src/rpc/request.rs, src/service.rs, src/syncerd/bitcoin_syncer.rs, src/walletd/runtime.rs
Skips over everything in swapd/
=> Some clippy fixes

.github/workflows/test.yml, tests/swap.rs
Adds a functional swap test for manually sweeping bitcoin from a funding address.
=> Functional tests: Add bitcoin manual sweep test

tests/swap.rs, tests/utils/config.rs, tests/utils/fc.rs
The name of the commits demonstrate what this PR does. Basically, only some small improvements for the warnings the linter was throwing.
=> Some tests improvements (fix warnings, etc)

tests/swap.rs
Closes #543
The last pull request (#667) was marked as closed for some reason.
=> Fix warning in functional-swap test

Cargo.toml, tests/cfg/config.yml, tests/docker-compose.yml
yaml's linter was going brrr
This also makes formatting more uniform, and makes Cargo.toml comply with dprint's config.
=> Improve formatting

src/syncerd/bitcoin_syncer.rs
This is a quick fix for the problem reported by @Lederstrumpf on IRC:
I just ran into this: bitcoin syncer panics when sweeping if fee estimate exceeds value of amount to be sweeped:
https://github.com/farcaster-project/farcaster-node/blob/26a46f57643c9dee92d565119fd920364544a480/src/syncerd/bitcoin_syncer.rs#L458
```
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', src/syncerd/bitcoin_syncer.rs:458:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> Syncer: Check for dust amount in sweep bitcoin method

src/grpcd/proto/farcaster.proto, src/grpcd/runtime.rs, tests/grpc.rs
This allows the grpc endpoint to make use of the list offers and their status selector.
=> Grpc: Support list offers endpoint

src/bus/info.rs, src/grpcd/proto/farcaster.proto, src/grpcd/runtime.rs, src/swapd/runtime.rs
Adds the trade role, swap role, and node id of the connected counterparty to the swap Runtime and the SwapInfo structs.
=> Add richer data to the swap info

CHANGELOG.md, Cargo.toml
Fix crate keywords and update changelog for release 0.5.0
=> Chore: prepare release 0.5.0

src/swapd/swap_state.rs
=> Alice: broadcast cancel tx eventually even if Alice overfunded

CHANGELOG.md
Update changelog for next release
=> chore: update changelog for v0.8.0

src/swapd/runtime.rs, src/swapd/swap_state.rs
Only log on debug when a service sends Hello to swapd
Create dedicated function for logging monero maturity
=> Swapd: Logging improvements

src/syncerd/bitcoin_syncer.rs, src/syncerd/monero_syncer.rs
This should consume minimally more resources, while offering 10x faster processing times
=> Syncer: Lower the time spent sleeping on the syncer receiver

src/swapd/runtime.rs, src/swapd/swap_key_manager.rs, src/swapd/swap_state.rs, src/swapd/syncer_client.rs
The key manager now returns a bundle of transactions for each Alice and Bob.
=> Swap: Move transactions from Runtime to State machine

src/bus/types.rs, src/cli/command.rs, src/databased/runtime.rs, src/grpcd/runtime.rs, src/swapd/runtime.rs, src/swapd/swap_key_manager.rs, src/swapd/swap_state.rs, src/syncerd/monero_syncer.rs, tests/monero.rs
=> Swap: Move AccLockHeight from Runtime to State

docs/Home.md, docs/Usage.md, docs/Using-Docker.md
This fixes some regression introduced by the sync wiki CI
=> Docs: resync with latest doc version

docs/Home.md, docs/Install-guide.md, docs/Run-local-swap.md, docs/Testing-with-farcaster.dev.md, docs/Usage.md, docs/Using-Docker.md
This with #902 should fix the `docs/ <> wiki` synchronization.
=> Doc: touch files to trigger CI workflow

CHANGELOG.md
This prepare the changelog for next release (some PR are removed if not related to features/codebase)
=> Chore: update changelog for release 0.8.2

src/swapd/swap_key_manager.rs
=> Swapd: Don't add color coding to progress message

src/swapd/runtime.rs, src/swapd/swap_key_manager.rs, src/swapd/swap_state.rs
=> Swapd: Simplify commitment creation

src/swapd/runtime.rs, src/swapd/swap_key_manager.rs, src/swapd/swap_state.rs
Goal of the refactor was to reduce the amount of code inside the swapd runtime. This should make it easier to read and prepare a future refactor for implementing better Traits.
=> Swapd: Some simple refactors

farcasterd.toml, src/cli/command.rs, src/config.rs, src/farcasterd/trade_state_machine.rs, src/grpcd/runtime.rs
Allows to express lower and upper bounds for each assets on each network, used when validating maker/taker deals.
=> Feat: cli enhancement and improved deal validation

src/swapd/swap_key_manager.rs, src/swapd/swap_state.rs
Some simple refactors for reducing code duplication.
=> Swapd: Refactor key manager init

src/grpcd/runtime.rs
Add missing implementation when the funding list return type is Monero.
Styling: reorg and shorten imports.
=> Fix(grpc): list Monero funding addresses

CHANGELOG.md
Update changelog for release 0.8.4
=> Chore: prepare release 0.8.4

src/swapd/runtime.rs, src/swapd/swap_state.rs, src/swapd/syncer_client.rs
Transactions that initially fail to broadcast are now attempted to be re-broadcast on every block height increase.
=> Swapd: Retry tx broadcast

src/grpcd/proto/farcaster.proto, src/grpcd/runtime.rs
This should work the same as the get-balance cli call.
=> Grpcd: Add GetBalance endpoint
