- src/farcasterd/runtime.rs
after swapd is successfully launched, the swap is removed from making_swaps and
added to running swaps.
> add initiated maker swap to running swaps

- Cargo.toml
- src/farcasterd/mod.rs
- src/farcasterd/runtime.rs
- tests/rpc.rs
So far, this starts a cli and a farcaster daemon, then creates an offer from the defaults. Kills `farcasterd` to clean up the test, but does not kill its children yet. I'll open up a separate PR for the management of children.
> integration test framework

- Cargo.toml
- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/mod.rs
- src/farcasterd/runtime.rs
- src/rpc/request.rs
- tests/rpc.rs
builds on #27 to kill child processes of `farcasterd` at the end of tests before killing `farcasterd`.
> manage farcasterd children

- Cargo.lock
- src/farcasterd/runtime.rs
rebreaks argument parsing for tests, but unbreaks binaries built with `--all-features` as reported by frix, so overall win ¯\\_(ツ)_/¯
> remove integration_feature conditional from farcasterd::runtime

- Cargo.lock
- Cargo.toml
Fix `farcaster-core` dependencies to commit https://github.com/farcaster-project/farcaster-core/commit/7ccfe1bcd1eb1961a2f678e640b0ebc8ce215ab4.
This is done because `farcaster-core` will have some big refactoring and will be unstable for some time.
**This should not break the current build (I tested) as it uses the same commit (see Cargo.lock diff) as before, but doing `cargo update` will not update the revision for core anymore, and thus become safe.**
> Fix farcaster-core dependencies

- tests/rpc.rs
hardcoded serialized offer atm - should be read dynamically. since successful execution calls return unit type, testing is restricted to errors passed up - no validation of successful execution results.
> extend integration test to maker-taker

- Cargo.lock
- Cargo.toml
- shell/_swapd
- src/cli/opts.rs
- src/farcasterd/runtime.rs
- src/rpc/request.rs
- src/swapd/opts.rs
- src/swapd/runtime.rs
- src/walletd/runtime.rs
This PR starts integrating new core design with the latest refactoring. Work in progress, the node currently does not compile because of the new 'wallet' design in core and the fact that it is needed in `swapd` for actions on the `commit/reveal` phase.
Core points to https://github.com/h4sh3d/farcaster-core/tree/feature/encoding you can see the draft on core at https://github.com/farcaster-project/farcaster-core/pull/59
> Update core library

- shell/_peerd
- shell/_peerd.ps1
- shell/peerd.bash
- src/bin/farcasterd.rs
- src/bin/peerd.rs
- src/bin/walletd.rs
- src/cli/command.rs
- src/farcasterd/runtime.rs
- src/lib.rs
- src/peerd/opts.rs
- src/peerd/runtime.rs
- src/rpc/request.rs
- src/swapd/runtime.rs
- src/walletd/opts.rs
- src/walletd/runtime.rs
Added  general mechanism for doing callbacks, such as: 
```
MakeOffer (orig req) -> return GetKeys (req) -> 
(rep) Keys -> continue MakeOffer (orig req)
```
Mechanism uses early return to exit original request, into the fallback path
requesting the keys, uses a RequestId to identify what pending_request to call
back, using recursion to continue the pending_requests following up receiving Keys back from wallet, such that the return is from the original request -- just proceding with execution
> Farcasterd retrieve key from wallet before launching peerd

- Cargo.lock
- Cargo.toml
- src/service.rs
Update `farcaster_core` to point on https://github.com/farcaster-project/farcaster-core on `main` and `amplify` dependencies to the latest versions.
General update of `Cargo.lock` and fix of new method name on `amplify::Getters` derive macro in `service.rs`.
> Update farcaster core and amplify

- .github/workflows/test.yml
- .gitignore
- src/syncerd/bitcoin_syncer.rs
- Run `cargo fmt` in nightly
- ~Add namespace for inproc monero bridge (see if it resolve the issue at https://github.com/farcaster-project/farcaster-node/runs/4153268390?check_suite_focus=true#step:7:1710)~
- Ran cargo fmt
- Ignore generated folder when running functional tests
Work already done in https://github.com/farcaster-project/farcaster-node/pull/172
> Functional tests and CI

- README.md
- doc/README.md
- doc/docker-stack.md
- doc/local-swap.md
Move remote client in docker documentation, the `Usage` section is now closer to the top for readers going through the readme.
> Simplify main readme

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- src/syncerd/bitcoin_syncer.rs
- tests/functional.rs
Based on #172.
- Split tests atomically, no big wrapper functions
- Remove no-capture, if test fail stdout is printed anyway, cleaner logs for passed tests
- Run all tests (bitcoin and monero ones) in sequence within 1 unique thread
> Individual tests atomic

- Cargo.lock
- Cargo.toml
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/syncer_state.rs
- tests/README.md
- tests/docker-compose.yml
- tests/functional.rs
Replace the get verbose transaction call to Electrum server by 3 different calls allowing to extract the tx confirmations and the block hash.
> Replace get verbose transaction

- src/syncerd/monero_syncer.rs
These might have done more harm than good.
The wallets are anyway generated from a manged height already.
> Monero syncer: Remove refresh

- src/syncerd/bitcoin_syncer.rs
- src/syncerd/syncer_state.rs
- tests/functional.rs
The Bitcoin syncer now uses the same seen/unseen transaction part like the monero syncer. Unseen transactions are continuously polled, until they are either mined or detected in the mempool. Subsequent polling is only done if either the block hash or block height changes.
> Bitcoin syncer: Use unseen transaction pattern

- src/swapd/runtime.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
- tests/functional.rs
This is supposed to fix #254 , please test if this makes the excessive monero-wallet-rpc logging disappear.
> Monero syncer: Add restore height for sweep wallet

- src/bin/farcasterd.rs
- src/config.rs
Fix #261
When launching farcasterd, if no config find is found a new one is created with the default values.
> Create config file if not present

- Cargo.lock
Fix #208
Update `zeroize` and `zeroize_derive` to avoid `zeroize_derive` yanked version `1.1.0`
> Update zeroize deps to avoid yanked deps

- .clippy.toml
- .github/workflows/static-analysis.yml
Relax clippy validation because of Rust 1.57 and add msrv in clippy for future potential breaking rules with our current minimal stable Rust version 1.55.
> Clippy warns and msrv

- README.md
- compose/farcasterd.toml
- doc/docker-stack.md
- doc/local-swap.md
- docker-compose.yml
- farcasterd.toml
- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/config.rs
- src/farcasterd/runtime.rs
- tests/functional-swap.rs
- tests/rpc.rs
Fix #262, fix #216
Change swap-cli make|take command to use named arguments an allow better usage of default values (some have been updated). Remove default values for exchanged amounts.
Update overall documentation for docker with new config and new command line arguments.
> Modify doc and swap-cli

- .github/workflows/test.yml
- .gitignore
- tests/.farcasterd_1.ci.toml
- tests/.farcasterd_2.ci.toml
- tests/README.md
- tests/docker-compose.yml
- tests/functional-swap.rs
- tests/functional.rs
- Use services instead of docker-compose (compose is still use and documented for local tests)
- Use one matrix for all three tests: `bitcoin`, `monero`, and `swap`
- Log output of farcaster daemon for `swap` tests and upload the artifact
> Use GH action services for functional tests

- Cargo.lock
- README.md
- doc/local-swap.md
- shell/_swap-cli
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
Fix #276
- Bump core from `0.4.0` to `0.4.2`
- Display offer upon taking nicely with new core Display impl
- Use new core `FromStr` variants for cmd line argument parsing, remove weird `ECDSA` for Bitcoin (keep old variants compatible)
New offer display:
```
Want to buy 0.00002450 BTC for 0.040000000000 XMR?
Carefully validate offer!
Trade counterparty: 0372fcf99da1a6f28714f10c35da3e869dc98672603e0a4c0f5bba06b91a507dff@127.0.0.1:9735
Network: Testnet
Blockchain: Bitcoin<SegwitV0>
- amount: 0.00002450 BTC
Blockchain: Monero
- amount: 0.040000000000 XMR
Timelocks
- cancel: 4 blocks
- punish: 5 blocks
Fee strategy: Fixed: 1 satoshi/vByte
Maker swap role: Bob
Take it? [y/n]
n
Rejecting offer
```
> Core update and Display/FromStr improvements

- Cargo.lock
- Cargo.toml
- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/runtime.rs
- src/rpc/request.rs
Lists public offer ids. First step towards addressing #287.
Requires merge of https://github.com/farcaster-project/farcaster-core/pull/195.
> cli: add command to list PublicOffer

- .dockerignore
- .github/workflows/test.yml
- Cargo.toml
- Dockerfile
Fix #323
Remove requirement to have libzmq accessible on the machine at build time and use the vendored feature.
> Use vendored zmq

- README.md
While linking the configuration heading where it previously was
> readme: moved the configuration towards the end ease the flow directly into usage

- src/farcasterd/runtime.rs
- src/walletd/runtime.rs
Fix #296
- Add for _INFO, DEBUG, ERROR, WARN_ log levels the `{short swap id} | ...` prefix
- Print full offer id when registered in farcasterd (same format as starting swaps)
> Append swap id in walletd logs

- farcasterd.toml
- shell/_farcasterd
- shell/_farcasterd.ps1
- shell/farcasterd.bash
- src/config.rs
- src/farcasterd/opts.rs
- src/farcasterd/runtime.rs
Move the `--auto-fund` parameter from cmd line argument to `farcasterd.toml` config file and added list of node and paramter to use per network when auto-funding is enable.
The funding logic stays exactly the same, just where parameters come from has changed. The pattern matching has changed to include the network selection to see if auto-funding is configure or not.
**Auto-funding will work only if `auto_fund` is set to true and if the network is registered in the config, otherwise manual funding is used.**
> Extract auto funding in config

- src/swapd/runtime.rs
- tests/functional-swap.rs
Replace #175 
Set btc to 1 block to consider final and xmr to 5 blocks (even if not spendable before 10).
This is temporary and will be changed towards #320.
> Update finality threshold for btc/xmr

- src/bin/peerd.rs
- src/farcasterd/runtime.rs
- src/peerd/opts.rs
- src/peerd/runtime.rs
- src/rpc/request.rs
> Peerd single port multi connections

- src/swapd/runtime.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/types.rs
- tests/functional.rs
Based on #388
@zkao , I am loosing quite some precision with the amount parsing. The reason I'm using the bitcoin amount type is that sending a float in the emitted Event is kind of hard to get right, since we can't hash floats. Do you want a string instead, that can then be parsed into a float?
> Fee estimation

- farcasterd.toml
- src/config.rs
- src/farcasterd/runtime.rs
Adds optional userpass authentication for bitcoin-rpc when autofunding. When both cookie and userpass authentication credentials are provided, it defaults to cookie authentication.
> add userpass auth option for bitcoin rpc

- .github/workflows/package.yml
- Dockerfile
Current docker build is failing on main because we forgot to bump the MSRV in Dockerfile. This PR:
- update the Rust version to latest in dockerfile
- use Debian bullseye instead of Buster to build and run farcasterd
- always try to build the image (PR and push main) but only push the image in registry on push main
> Fix docker build

- tests/functional-swap.rs
Doubles the sleep time to ensure all swaps are funded and locked.
> Functional swap test: Improve parallel swap test reliability

- .github/workflows/test.yml
- tests/.farcasterd_1.ci.toml
- tests/.farcasterd_1.toml
- tests/.farcasterd_2.ci.toml
- tests/.farcasterd_2.toml
- tests/README.md
- tests/docker-compose.yml
- tests/functional.rs
Update the CI functional tests container versions:
- bump bitcoin to `22.0`
- bump monerod to `0.17.3.2`
- bump monero-wallet-rpc to `0.17.3.2`
Syncer and tests must be rewritten to work with bitcoin `23.0` and electrs `0.9.x`. This is out of scope of this PR.
> Bump CI container versions

- src/peerd/runtime.rs
- src/rpc/request.rs
Setting the peer identity will be handled by the peer connection establishment itself.
> Peerd: Remove UpdateSwapId request handling

- src/cli/command.rs
- src/farcasterd/runtime.rs
- src/rpc/client.rs
- src/rpc/request.rs
- src/service.rs
- src/swapd/runtime.rs
- src/syncerd/runtime.rs
Similar but slightly different approach from #438
Result:
```
swap-cli progress 0x32e3cdb8ab4b58be737def0fe6c75cc1cf045a7593df975f64a0dc60177a6fa8
---
progress:
- message: this is a message
- transition: state1 -> state2
- success: swap is successful
- failure:
code: 1
info: info error here
```
> Make progress serializable - alternative

- src/peerd/runtime.rs
- src/rpc/request.rs
Only some of the messages should be allowed through the PeerdReceiverRuntime to the peerd Runtime. I don't like this explicit listing of messages, is there some other method to select this subset of enum variants?
> Peerd: Only send whitelisted Msg's over the bridge

- Cargo.toml
- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/runtime.rs
- src/rpc/client.rs
- src/rpc/request.rs
This PR allows `progress` to pass a flag `-f|--follow` to continuously receive progress update until ctrl-c is pressed or termination condition is met: a request success or failure is received.
When the flag is not passed, the behavior is the same as previously, a one shot result in yaml format is returned.
When the client is in follow mode a first request is send to farcasterd to register itself in the progress subscription list, when a client register to a swap farcasterd send the queue back to the client. After registering the client loops on all messages until termination condition is met. When farcasterd receives a message related to some swap progress the message is forwarded to all client subscribed to it. If the forwarding fails the client is removed from the sub list.
```
| …
```
> feature: make progress waiting on new messages

- src/bin/peerd.rs
- src/farcasterd/runtime.rs
- src/service.rs
Uses the same heuristic as the `connect_peer` method.
> Farcasterd: Check if peerd listen launched successfully

- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
This completes #457 by adding an endpoint to display information about an offer. It is similar to the `take` command but does not interact with any of the other microservices.
> Cli: Add endpoint to print information about a passed-in offer

- src/databased/runtime.rs
- src/rpc/request.rs
Add endpoints to the database to persist addresses and their private keys. Does not include actual integration with the rest of the codebase, e.g. persisting the addresses when the funding keys are created.
> Persist funding address secret key

- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/runtime.rs
- src/rpc/request.rs
- src/swapd/runtime.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/syncerd/bitcoin_syncer.rs
- src/walletd/runtime.rs
- tests/functional-swap.rs
Based on #499 and #485 .
A swap should be cancelable by the user if its side has not locked any coins yet.
For Alice, this means a swap can be canceled without additional handling up until she reaches state RefundSigA. Once she reaches RefundSigA, the XMR funding address is displayed and may thus contain locked coins. At the point, the swap should just follow the rest of  the protocol. 
For Bob, this means a swap can be canceled without additional handling as long as it still is in its original start state. If it is in commit, reveal, or corearb state and has not yet received the refund procedure signatures from Alice, it additionally attempts to sweep any coins that were sent to the funding address.
~Because of the sweeping, the syncers need to keep on running after the user has canceled …
> Cancel swap

- src/databased/runtime.rs
- src/rpc/request.rs
Adds persistance for offers. Offers can now be written to a separate table in the lmdb database.
They can be retrieved by selecting their status. The `OfferStatus` and `OfferStatusSelector` are separated to allow for extension of their criteria. For example saving addresses in the `Open` status, or `SwapId`s in the `InProgress` status, and selecting offers based on other common criteria, like amounts.
> Persist offer history

- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/mod.rs
- src/cli/opts.rs
- src/databased/runtime.rs
- src/farcasterd/runtime.rs
- src/rpc/mod.rs
- src/rpc/request.rs
Persist open, in progress and ended offers. Adds an option to `list-offers` to select offers by their status. This allows the user to query trade history.
> Offer history

- src/swapd/runtime.rs
- src/swapd/swap_state.rs
Alice should be able to cancel the swap up until the point where Bob's lock has confirmed.
> Swap: Allow cancel for alice refundsig before arb lock

- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/swap-cli.bash
- src/cli/command.rs
- src/cli/opts.rs
- src/databased/runtime.rs
- src/farcasterd/runtime.rs
- src/rpc/request.rs
- src/walletd/runtime.rs
This can be used to salvage funds from funding addresses in case something goes wrong.
> Cli: Implement sweep address call

- src/swapd/mod.rs
- src/swapd/runtime.rs
- src/swapd/swap_state.rs
This also solves the problem where a checkpoint of the same state would be written to the database again on restore.
> Swap: Ensure a checkpoint is only set once and in the correct order

- src/swapd/runtime.rs
- src/swapd/syncer_client.rs
- tests/functional-swap.rs
Solves the race condition described in #515. The syncer state (syncer client) now keeps track of transactions that are pending broadcast. Once their broadcast has been confirmed by the syncer, they are removed again.
> Fix Checkpoint race condition

- src/rpc/request.rs
- src/swapd/runtime.rs
- src/swapd/swap_state.rs
Adds a public_offer to each swap state. Not sure if the swap state is the correct place to put it, as opposed to the Runtime, would be great to get your comment on this @zkao.
Also cleans up the swap GetInfo struct a bit.
Closes #458
> Swap: Add public offer to GetInfo

- .github/workflows/test.yml
- README.md
- doc/docker-stack.md
- doc/install-guide.md
- doc/local-swap.md
- docker-compose.yml
- shell/_farcasterd
- shell/_farcasterd.ps1
- shell/_peerd
- shell/_peerd.ps1
- shell/_swap-cli
- shell/_swap-cli.ps1
- shell/_swapd
- shell/_swapd.ps1
- shell/farcasterd.bash
- shell/peerd.bash
- shell/swap-cli.bash
- shell/swapd.bash
- src/farcasterd/runtime.rs
- src/opts.rs
- tests/README.md
- tests/utils/fc.rs
- tests/utils/mod.rs
To allow more granular settings in logger this PR switch from using one flag `--verbose` and instead make use of the `RUST_LOG` environment variable.
By default, if the env var is not set, the default is `farcaster_node=info`. This will display all info logs ONLY coming from farcaster node. In test the var is set to `farcaster_node=debug,microservices=debug`.
> Use `RUST_LOG` to configure loggers instead of `--verbose` flag

- src/databased/mod.rs
- src/databased/runtime.rs
- src/swapd/runtime.rs
- src/walletd/runtime.rs
We now have unlimited size zmq messages, so remove the checkpoint multipart chunking. :tada: :smile:
> Checkpointing: Remove multipart message chunking

- CHANGELOG.md
The initial list has been generated by github. I removed PRs that was only working on tests/ci/doc with no real information about "code change".
This list is not perfect but it is sufficient as we didn't released a version in >6 months so the changelog is too big anyway for being super precise.
> chore: update changelog with latest meaningful PRs

- .github/workflows/binaries.yml
- .github/workflows/package.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test.yml
This tries to reduce the number of actions triggered in PRs and in main.
E.g. do not run the full tests if only markdown files are touched.
> ci: filter by paths to reduce actions triggered

- Cargo.lock
- Cargo.toml
- doc/docker-stack.md
- doc/install-guide.md
- docker-compose.yml
- src/syncerd/monero_syncer.rs
- tests/docker-compose.yml
- tests/monero.rs
- tests/swap.rs
This bumps Monero clients to 0.18.0.0 like #614 does. If the other PR gets merged first, I'll update this one.
> Bump code to monero-rpc-rs and bump Monero clients to 0.18.0.0

- .github/workflows/test.yml
As mentioned on IRC lws `latest` tag points to 0.18 which does not work yet, this should fix the CI so we can still validate other PRs until latest versions are stabilized.
> fix: pin lws version to match 0.17

- .github/workflows/test.yml
As mentioned in https://github.com/farcaster-project/farcaster-node/pull/655#issuecomment-1214888888 we should remove nightly usage in CI instead of bloating the `Cargo.toml` file. Code coverage is not used and not representative so we can drop it.
This should allow the CI to pass with latest core and regression in rust-nightly.
> ci: remove nightly usage

- src/walletd/runtime.rs
The funding is handled by swapd exclusively.
Additionally, with the implemented fee estimation, is displays an incorrect amount.
> Walletd: Remove funding information

- src/syncerd/bitcoin_syncer.rs
Closes #628. Replaces #695, see it for motivation & details, but now reusing existing `unseen_transaction_polling`. Tested extensively on farcaster.dev. Commits are noisy, so squash merge.
> electrs failures: reattempt `script_get_history(...)`

- src/error.rs
- src/syncerd/bitcoin_syncer.rs
Ensure that once a transaction is found it is treated by minimum as unconfirmed.
> Syncer: normalize treatment between different failure cases when polling transactions

- src/swapd/runtime.rs
- src/syncerd/monero_syncer.rs
as reported on irc, all sustained maker/taker relationships would eventually halt. this was primarily down to monero sweep sometimes failing: if the daemon would intermittently not respond, the sweep would fail and not be reattempted (this lack of retry was introduced by a code refactor). Thus the swap would never finish for Bob, only Alice.
now sweeps are again always reattempted when this occurs.
> fix sweep failures on intermittent daemon irresponsiveness

- src/bus/msg.rs
- src/peerd/runtime.rs
Log outgoing and incoming p2p protocol message in a friendly manner with the corresponding swap id. Next step is to add them in the progress stack too, but I let it for another PR that improve the overall progress feature.
> feat: log as info level p2p msg sent and received per swap

- Cargo.lock
- Cargo.toml
- src/bus/rpc.rs
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/mod.rs
- src/farcasterd/runtime.rs
- src/farcasterd/stats.rs
- src/service.rs
- src/syncerd/runtime.rs
- src/syncerd/types.rs
Based on #707 
This PR introduce the implementation of `info <blockchain> <network>` and `list-tasks <blockchain> <network>` to return the list of tasks a _syncer has received_ (and not the current list of tasks, this need a bit more work because of the current syncer state).
It also extend the `info` command to return the `stats` that are printed in the logs (number of funded, swaped, canceled, etc).
> Feat: improve swap-cli commands

- src/farcasterd/runtime.rs
- src/farcasterd/stats.rs
- src/farcasterd/trade_state_machine.rs
- src/peerd/runtime.rs
- src/service.rs
- src/swapd/runtime.rs
- src/swapd/syncer_client.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/walletd/runtime.rs
Based on #707
Rework some logs to add uniformity and standardize the code to apply colors.
TODO
> Style: improve logs and colors

- src/walletd/runtime.rs
This allows us to circumvent any dangers incurred from getting the btc addresses.
> Bugfix: Use refund address for sweeping bitcoin through walletd

- src/swapd/syncer_client.rs
Fix issue reported by @Lederstrumpf on IRC
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/swapd/syncer_client.rs:368:35
```
This PR change the printing logic of this dangerous `unwrap` (the one before is safe as the condition checks for `is_some`) to not print the variable `confirmations`. Previous code checked if the tx was inserted in the final tx map, now if retrieve the value in the map and print `final` or `non-final`.
A general comments on this piece of code: the map structure is not really used as I only found `insert(txlabel, true)` and nothing else, this is equivalent to simply using a set.
> Fix(syncer_client): remove dangerous unwrap in handle tx confs

- Cargo.lock
- Cargo.toml
- src/bus/bridge.rs
- src/bus/mod.rs
- src/databased/runtime.rs
- src/event.rs
- src/farcasterd/runtime.rs
- src/farcasterd/syncer_state_machine.rs
- src/farcasterd/trade_state_machine.rs
- src/grpcd/proto/farcaster.proto
- src/grpcd/runtime.rs
- src/swapd/runtime.rs
- tests/cfg/fc2.ci.toml
- tests/cfg/fc2.toml
- tests/grpc.rs
This pull requests implements additional endpoints for listing peers and checkpoint entries, restoring checkpoints, making and taking offers, revoking offers, aborting swaps, and sweeping coins. 
The grpc server can now handle sending to arbitrary services. Additionally, sending messages back to the client has been extended for including grpc as a possible client, where applicable.
In order to route all possible grpc request messages across all possible service busses through the grpc daemon bridge, a separate BridgeMsg message type was added, acting as a wrapper for the messages and their destination.
Getting full test coverage on this PR is nigh impossible, since there are an abundance of failure paths. This PR does extend the tests though by adding a happy path test for each possible …
> Feature: Extend Grpc implementation

- src/bus/ctl.rs
- src/bus/p2p.rs
- src/peerd/runtime.rs
- src/swapd/runtime.rs
- src/swapd/syncer_client.rs
Peer messages sent to a remote peer are now cached until the remote peer has replied with a corresponding receipt.
If the connection fails in a listener spawned peerd, the cache is emptied before peerd shuts down and the messages are sent back to their respective origin (swapd). Swapd then processes them into its own cache.
If the connection fails in a connecting peerd, the cache is only emptied once the reconnect has been a success. Messages are not sent back to their origin.
> Peerd: Use message receipts to confirm receival

- .github/workflows/test.yml
- tests/docker-compose.yml
This PR bumps `electrs` and Monero `rpc`, `wallet` and `lws` version to the latest container images we have on [containers](https://github.com/farcaster-project/containers)
> Ci: update containers

- farcasterd.toml
- src/bin/grpcd.rs
- src/config.rs
- src/farcasterd/runtime.rs
- src/grpcd/opts.rs
- src/grpcd/runtime.rs
- tests/cfg/config.yml
- tests/cfg/fc1.ci.toml
- tests/cfg/fc1.toml
- tests/cfg/fc2.ci.toml
- tests/cfg/fc2.toml
- tests/grpc.rs
- tests/utils/config.rs
Fix #468, fix #466, fix #467
This PR is a rework of the gRPC configuration in `farcasterd.toml` config file. It updates the previous config and add a new flag to control the bind ip address.
**This PR also rename the `auto_fund = true` option into `enable = true` for auto-funding**
> Feat: new grpc config options

- src/grpcd/runtime.rs
Instead of letting each handler handle errors by itself, use a single helper function. This gets rid of most of the code duplication in the grpc handlers.
> Grpc improve error handling

- src/bus/types.rs
- src/databased/runtime.rs
- src/farcasterd/trade_state_machine.rs
- src/swapd/runtime.rs
Also adds the required members to a swap's checkpoint to allow us to get the required CheckpointEntry members from a a swap checkpoint. 
This is another breaking change to the database schema.
Based on #769
> Database: Add NodeInfo to CheckpointEntry

- src/bus/info.rs
- src/bus/types.rs
- src/databased/runtime.rs
- src/farcasterd/runtime.rs
- src/farcasterd/stats.rs
- src/farcasterd/trade_state_machine.rs
- src/grpcd/proto/farcaster.proto
- src/grpcd/runtime.rs
- src/service.rs
- src/swapd/mod.rs
- src/swapd/runtime.rs
- src/swapd/state_report.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/swapd/temporal_safety.rs
- src/walletd/runtime.rs
- tests/swap.rs
There are now three possible progress messages that a swap can issue. I message is just a string containing information. A transition goes from an old state to a new state. A state update updates the current state. Farcasterd only keeps the latest state update around, any previous state updates are discarded.
The progress now serves additional information about the confirmation status of various transactions during a swap. Additionally, it provides the block height of a running swap daemon.
I can be pretty flexible with the provided information here, so please let me know what additions / changes / re-designs you want.
Sample Output:
```
> swap1-cli progress 0xaf373e2400556909ab5b90959242979ac6bb05e0c48888d24533095fc7ead6ab                          
progress:
- message: Proposing to take …
```
> Add richer data to the progress messages

- src/swapd/runtime.rs
Convert HashMap to Vec to use Vec's derived StrictEncoding. Encode checkpoints by draining a hashmap into a Vec of tuples.
> Swapd: Simplify checkpoint encoding

- src/swapd/runtime.rs
- src/syncerd/monero_syncer.rs
Based on #761
Correct log message for when monero reaches the buyer.
Log incoming monero syncer watch addr and tx tasks on debug.
Record and checkpoint the monero address creation height.
Improve formatting of two log messages.
Swapd: Safer behaviour around publishing transaction. Always publish the refund transaction if you can, inform the user if punish was possible in the meantime
> Swapd: Some patches and improvements

- src/bus/ctl.rs
- src/databased/runtime.rs
- src/farcasterd/runtime.rs
If a swap is killed before funding, no checkpoint is written, but the offer status of the involved offer is still set to InProgress. Move the persisted offer status from InProgress to Abort on restart.
> Farcaster: Cleanup dangling swap info on restart

- src/bus/types.rs
- src/cli/command.rs
- src/databased/runtime.rs
- src/error.rs
- src/grpcd/runtime.rs
- src/walletd/runtime.rs
Bitcoin addresses now additionally store an optional swap_id.
Monero addresses additionally store an optional swap_id and optional
creation height.
Also add cleaner database encoding error handling.
This allows us to know from which height to sweep the Monero funding address and to which swap the funding addresses belong when cleaning up dangling swap data.
> Database: Change secret key encoding

- tests/grpc.rs
This fixes an issue with the grpc tests, where they would fail if no swap id was available after 5, respectively 15 seconds. The added code retries the request until the swap id is successfully retrieved.
> Tests: Use retries until swap id is available in grpc test

- src/bus/ctl.rs
- src/bus/types.rs
- src/cli/command.rs
- src/cli/opts.rs
- src/farcasterd/runtime.rs
- src/farcasterd/syncer_state_machine.rs
- src/grpcd/proto/farcaster.proto
- src/grpcd/runtime.rs
- src/swapd/runtime.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
This adds a cli command "health-check" for checking the configuration and required environment (e.g. the to-be-connected coin daemons, wallets, etc.) of a syncer.
To this end, this commit also adds a HealthCheck event that can be dispatched to a syncer. The various syncers make simple calls to the respective coin daemons and report their success back in the form of a HealthResult event.
The "health-check" command makes use of the syncer state machine in farcasterd to startup syncers and route calls back to the client.
> Cli: Implement endpoint for checking syncer health

- src/grpcd/runtime.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
... and replace them with a `LocalSession`. `LocalSession` is the session that is used across the microservices.
> Busses: Remove transcoders from bridge bus senders

- src/bus/p2p.rs
- src/farcasterd/runtime.rs
- src/swapd/runtime.rs
The maker now replies to the taker with  the `OfferNotFound` message in case the offer is no longer available. The taker, on receipt, then aborts the already spawned swap.
> Farcaster: Handle take offer failure

- src/bus/bridge.rs
- src/grpcd/runtime.rs
If there is an error within the grpc server runtime, it will destroy the server and send a notification to the zmq runtime. The zmq runtime then restarts the grpc server.
> Grpc: Handle recoverable server runtime panics

- src/cli/command.rs
- src/farcasterd/syncer_state_machine.rs
- src/grpcd/runtime.rs
- src/swapd/runtime.rs
- src/swapd/syncer_client.rs
- src/swapd/wallet.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
- tests/bitcoin.rs
- tests/monero.rs
This allows us to use the recorded creation height of a Monero address when sweeping from that address.
> Feat: Use creation height when sweeping Monero

- src/farcasterd/trade_state_machine.rs
A restored maker swap will now launch a peerd listener. Once a restore transitions into `SwapdRunning` the `expected_counterparty_node_id` is used to identify the correct incoming connection.
> Relisten maker restore

- src/farcasterd/trade_state_machine.rs
Fixes an issue where the reconnect message would be triggered by a Hello of an arbitrary peer.
> TSM: Check if Hello is coming from peerd

- Cargo.lock
- Cargo.toml
- src/farcasterd/trade_state_machine.rs
- src/syncerd/monero_syncer.rs
- tests/monero.rs
- tests/utils/fc.rs
Use the new monero-rpc builder pattern for instantiating monero rpc clients.
> Deps: Bump monero-rpc to latest version (v0.3.2)

- src/grpcd/proto/farcaster.proto
- src/grpcd/runtime.rs
- tests/grpc.rs
This adds richer information to returned offers, allowing the user of the API to use offers directly without going through the OfferInfo endpoint.
> Grpc: Added decoded OfferInfo field to returned offers

- src/databased/runtime.rs
Instead of swallowing some of the strict encode errors, transparently handle them at the database call site. 
Also fixes a bug, where the Monero addresses were written to the bitcoin address db.
> Database: Improve error handling

- src/swapd/runtime.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
There's no reason to keep this within the syncer state since it's only
read from within the swap state machine. Instead, read it from `swapd.runtime.public_offer.offer.{arbitrating,according}_amount_`. Closes #837 and closes the more loosely phrased #271.
> remove swapd.runtime.syncer_state.{bitcoin,monero}_amount

- src/syncerd/monero_syncer.rs
> Monero socks proxy

- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/swapd/wallet.rs
A bunch of small independent refactors segregated by commits not tracked by open issues. 
The commit 09387540ecce3f9314396ddd29582781a28925b4 (*couple swap role and wallet role when initiating maker*) I'm unsure about, but would like to discuss stronger coupling of swap roles and wallet roles in handling.
> Swapd: state refactors

- src/opts.rs
With our current default filter with exclude everything outside of `farcaster_node`, with this patch errors from e.g. microservices are displayed by default.
> Feat: log errors outside of farcaster too

- src/swapd/swap_state.rs
The message is already emitted when the AbortSwap is coming in.
> Swap state: Don't emit Bob aborted swap message twice

- src/farcasterd/runtime.rs
- src/farcasterd/syncer_state_machine.rs
If a call to the syncer from Farcasterd fails, task aborted may be emitted. Handle this case gracefully.
> Syncer State Machine: Handle Task Aborted

- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
- tests/bitcoin.rs
- tests/monero.rs
Adds a filter to the WatchAddress Task in order for the user to select incoming or outgoing transactions. The returned AddressTransaction's amount is either the sum total incoming amount if the incoming bool is true, or the sum total outgoing amount if the incoming bool is false.
> Syncer: Support Incoming and Outgoing AddressTransaction events

- README.md
Also adds a new badge for 'tests' status on `main`
See https://github.com/badges/shields/issues/8671 for more details
> Chore: fix url for ci badge

- src/swapd/runtime.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
Keep a list of broadcasted transactions and re-broadcast them when receiving a `None` confirmation event.
Also segregate the handling of syncer confirmations to the runtime and don't repeat the logic in the swap state machine.
> Swapd: Handle re-orgs and possible mempool drops of broadcasted txs.

- src/grpcd/proto/farcaster.proto
- src/grpcd/runtime.rs
- tests/grpc.rs
We need to keep the enum variant names distinct due to namespacing limitation.
See this stackoverflow post as an explanation.
https://stackoverflow.com/questions/68134072/different-enums-same-value-in-protobuf
> Grpc: Add deal suffix to selector

- src/grpcd/runtime.rs
When the client disconnects, its handler function is dropped. In this case, we should not error, but log a warning and continue the loop. Since we remove from the pending requests, no additional resources need to be dropped
> Grpc: Handle handler drops (usually on client disconnect)

- src/databased/runtime.rs
As an alternative: We could re-add these open offers to the farcasterd state and launch the listener.
> Database: Cleanup Open Deals as well on CleanDanglingDeals

- CHANGELOG.md
- Cargo.lock
Remove some warnings about yanked version on crates.io and prepare changelog for release `0.8.1`
> Chore: prepare release 0.8.1

- src/syncerd/monero_syncer.rs
These have the potential to burn the recipient's coins.
> Syncer(monero): Disregard unlock time transactions

- src/swapd/runtime.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
Storing the tasks within the same data structure is not really needed.
> Swapd: Refactor retrieving txs in syncer client

- src/bus/info.rs
- src/config.rs
- src/error.rs
- src/grpcd/runtime.rs
- src/swapd/wallet.rs
- src/syncerd/bitcoin_syncer.rs
Create a bunch of new error types and allign existing errors with common formatting.
> Errors: Wrap error types in Error enum instead of converting to Farcaster::Error

- src/farcasterd/syncer_state_machine.rs
- src/swapd/runtime.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
- tests/bitcoin.rs
- tests/monero.rs
- tests/utils/assert.rs
Add a dedicated address field in the Monero watch address addendum for the address instead of the public spend key.
Refactors a bunch of log lines towards using the default formatter.
Lastly, implements a dedicated Txid type for encoding txids. The syncer Txid type wraps either a bitcoin Txid, or a Monero tx hash
> Syncer: Some Refactors for better logging and ergonomics

- src/bus/types.rs
- src/cli/command.rs
- src/cli/opts.rs
Closes #825
By default no `local` configuration is provided, and local is only use in automated testing envs.
```
swap-cli health-check              <  check only mainnet and testnet
swap-cli health-check -s all       <  check all
swap-cli health-check -s {net}     < check only net
```
> Cli: health check ignore local by default

- .github/workflows/binaries.yml
- .github/workflows/static-analysis.yml
- src/config.rs
- src/databased/runtime.rs
- src/farcasterd/runtime.rs
- src/grpcd/runtime.rs
- src/swapd/runtime.rs
- src/swapd/syncer_client.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- tests/bitcoin.rs
- tests/grpc.rs
- tests/large_tx_serialization.rs
- tests/monero.rs
- tests/swap.rs
- tests/tooling.rs
- tests/utils/config.rs
- tests/utils/fc.rs
- tests/utils/misc.rs
Patches some left over clippy warnings and makes the github workflows error again if they detect a clippy or rustc linter finding.
> Make clippy annoying again

- src/event.rs
- src/farcasterd/syncer_state_machine.rs
Adds a new function that defaults to info level (same as previous behavior) and implements it with debug level for syncer state machine.
This is done to improve logs because health check task creates a lot of syncers, so a node connected with a GUI will generate a lot of noise.
> Logs: move syncer state transitions logs to debug level

- src/swapd/swap_state.rs
When receiving a transaction containing adaptor keys, extract them immediately and do not wait for finality.
> Swapd: Use transaction directly from transaction confirmations

- src/swapd/swap_key_manager.rs
> Swapd: Remove local trade role from SwapKeyManager

- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
- src/syncerd/syncer_state.rs
- src/syncerd/types.rs
- tests/bitcoin.rs
- tests/monero.rs
This was a remnant from when we used farcaster core consensus encoding for the syncer types.
> Syncer: Remove Boolean type and replace with raw type

- .github/workflows/docs.yml
Upstream default branch as changed from `master` to `main`, warning are thrown in CI and it seems that wiki -> doc doesn't work as expected...
> Ci: fix ref to wiki sync action

- Cargo.lock
- src/cli/opts.rs
- src/grpcd/runtime.rs
- tests/cli.rs
- tests/grpc.rs
- tests/swap.rs
Update core to version `0.6.2` and other dependencies.
Closes #403. Now the fee is only fixed and support fractional value such as 1.5 sat/vB with 1500 sat/kvB.
> Core: update to version 0.6.2

- src/swapd/mod.rs
- src/swapd/runtime.rs
- src/swapd/swap_key_manager.rs
- src/swapd/swap_state.rs
- src/swapd/syncer_client.rs
Implements the extended logging currently used in the swapd Runtime as a Trait used by both the Runtime and the syncer client.
> Swap: Add swap logging to syncer client

- .github/workflows/docs.yml
Correct wiki default branch is master.
> Ci: fix wiki branch

- .github/workflows/docs.yml
Reverts farcaster-project/farcaster-node#902
This branch is for the repo not for the wiki, this was correct. This patch was not needed and breaks the sync.
> Revert "Ci: fix wiki branch"

- Cargo.lock
- src/swapd/swap_key_manager.rs
Also remove new implementations for Alice and Bob key manager.
~Once the funding tx also implements strict decoding, we can get rid of the custom coding implementation on Bob as well.~
Updated core and removed the custom encoding implementation for Bob as well.
> Swapd: Simplify key manager encoding

- Cargo.lock
- src/bus/p2p.rs
- src/farcasterd/trade_state_machine.rs
- src/swapd/swap_key_manager.rs
- src/swapd/swap_state.rs
- Use `into()` to convert uuids, closes #914 
- Simplify reveal p2p message: use new merged reveal params and proof message
> Chore: update core to version 0.6.4

- CHANGELOG.md
- Cargo.lock
- farcasterd.toml
Update changelog and bump `monero` deps to allow lowercase `xmr` amount parsing.
> Chore: prepare changelog for release 0.8.3

- src/grpcd/runtime.rs
Network filter on `ListDealsRequest` was not always applied.
> Fix: filter by network all deal list responses

- src/swapd/state_report.rs
Fix the error where the accordant locked boolean was using the arbitrating finality parameters.
> Fix(state report): accordant lock used arbitrating params

- src/farcasterd/runtime.rs
- src/farcasterd/trade_state_machine.rs
This PR addresses two issues:
- An `event` could affect multiple `tsms`
- When restoring swapd make sure to reuse peerd connection if in `registered_services`
d894fba40dbade85589895bd4e85f91e683f288b only changes `..request_to_tsm` and not `..request_to_ssm` as I don't see any cases where the same issue would apply. This patch would be way cleaner with stabilized `drain_filter` feature, but it's not so... I did an ugly fn :)
> Fix(tsm): swaps restoring

- src/config.rs
- src/farcasterd/trade_state_machine.rs
Fixes #936.
Running on farcaster.dev with limits `0.0001-0.01 BTC`, `0.1-100 XMR`
> deal validation: only validate amount of outbound asset

- src/farcasterd/runtime.rs
Clippy change slipped through on missing rerun of workflow actions on #934.
> clippy quickfix

- src/syncerd/bitcoin_syncer.rs
- src/syncerd/monero_syncer.rs
* Calculate the the bitcoin address balance by adding both the confirmed and unconfirmed values.
* Print warn (and not debug) when balance retrieval fails.
* Correct log message when sending a bitcoin address balance task to a monero syncer.
> Syncers: Some address balance fixes
